2024-09-14 19:26:24 - INFO - Pipeline started.
2024-09-14 19:26:27 - WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
2024-09-14 19:26:31 - WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
2024-09-14 19:26:33 - WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 64] Host is down
2024-09-14 19:26:33 - WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
2024-09-14 19:26:33 - WARNING - Compute Engine Metadata server unavailable on attempt 1 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x14fbd4520>: Failed to resolve 'metadata.google.internal' ([Errno 8] nodename nor servname provided, or not known)"))
2024-09-14 19:26:34 - WARNING - Compute Engine Metadata server unavailable on attempt 2 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x14fbd5e10>: Failed to resolve 'metadata.google.internal' ([Errno 8] nodename nor servname provided, or not known)"))
2024-09-14 19:26:36 - WARNING - Compute Engine Metadata server unavailable on attempt 3 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x14fbd6380>: Failed to resolve 'metadata.google.internal' ([Errno 8] nodename nor servname provided, or not known)"))
2024-09-14 19:26:40 - WARNING - Compute Engine Metadata server unavailable on attempt 4 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x14fbd6740>: Failed to resolve 'metadata.google.internal' ([Errno 8] nodename nor servname provided, or not known)"))
2024-09-14 19:26:48 - WARNING - Compute Engine Metadata server unavailable on attempt 5 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x14fbd6980>: Failed to resolve 'metadata.google.internal' ([Errno 8] nodename nor servname provided, or not known)"))
2024-09-14 19:26:49 - INFO - Dask dashboard available at http://127.0.0.1:59650/status
2024-09-14 19:26:49 - INFO - Listing files from 2022-01-01 00:00:00 to 2022-01-01 00:00:00.
2024-09-14 19:26:49 - INFO - Processing file: gs://gcp-public-data-arco-era5/raw/date-variable-single_level/2022/01/01/total_precipitation/surface.nc
2024-09-14 19:26:54 - INFO - File processed: gs://gcp-public-data-arco-era5/raw/date-variable-single_level/2022/01/01/total_precipitation/surface.nc with shape: (3636140, 3). Time taken: 4.46 seconds
2024-09-14 19:27:04 - INFO - Saving the combined DataFrame to Parquet.
2024-09-14 19:27:04 - INFO - Data saved to Parquet. Time taken: 0.35 seconds
2024-09-14 19:27:04 - INFO - Pipeline completed successfully in 40.44 seconds.
2024-09-14 19:43:15 - INFO - Pipeline started.
2024-09-14 19:43:18 - WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
2024-09-14 19:43:22 - WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
2024-09-14 19:43:24 - WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 64] Host is down
2024-09-14 19:43:24 - WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
2024-09-14 19:43:24 - WARNING - Compute Engine Metadata server unavailable on attempt 1 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x1227b0bb0>: Failed to resolve 'metadata.google.internal' ([Errno 8] nodename nor servname provided, or not known)"))
2024-09-14 19:43:25 - WARNING - Compute Engine Metadata server unavailable on attempt 2 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x1227b1e70>: Failed to resolve 'metadata.google.internal' ([Errno 8] nodename nor servname provided, or not known)"))
2024-09-14 19:43:27 - WARNING - Compute Engine Metadata server unavailable on attempt 3 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x1227b2680>: Failed to resolve 'metadata.google.internal' ([Errno 8] nodename nor servname provided, or not known)"))
2024-09-14 19:43:31 - WARNING - Compute Engine Metadata server unavailable on attempt 4 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x1227b2a40>: Failed to resolve 'metadata.google.internal' ([Errno 8] nodename nor servname provided, or not known)"))
2024-09-14 19:43:40 - WARNING - Compute Engine Metadata server unavailable on attempt 5 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x1227b2f20>: Failed to resolve 'metadata.google.internal' ([Errno 8] nodename nor servname provided, or not known)"))
2024-09-14 19:43:41 - INFO - Dask dashboard available at http://127.0.0.1:59836/status
2024-09-14 19:43:41 - INFO - Listing files from 2022-01-01 00:00:00 to 2022-01-01 00:00:00.
2024-09-14 19:43:41 - INFO - Processing file: gs://gcp-public-data-arco-era5/raw/date-variable-single_level/2022/01/01/total_precipitation/surface.nc
2024-09-14 19:43:45 - INFO - File processed: gs://gcp-public-data-arco-era5/raw/date-variable-single_level/2022/01/01/total_precipitation/surface.nc with shape: (3636140, 3). Time taken: 4.17 seconds
2024-09-14 19:43:57 - INFO - Saving the combined DataFrame to Parquet.
2024-09-14 19:44:12 - INFO - Data saved to Parquet. Time taken: 15.43 seconds
2024-09-14 19:44:12 - INFO - Pipeline completed successfully in 56.89 seconds.
2024-09-14 19:45:23 - INFO - Pipeline started.
2024-09-14 19:45:26 - WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
2024-09-14 19:45:30 - WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
2024-09-14 19:45:32 - WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 64] Host is down
2024-09-14 19:45:32 - WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
2024-09-14 19:45:32 - WARNING - Compute Engine Metadata server unavailable on attempt 1 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x152bbcc10>: Failed to resolve 'metadata.google.internal' ([Errno 8] nodename nor servname provided, or not known)"))
2024-09-14 19:45:33 - WARNING - Compute Engine Metadata server unavailable on attempt 2 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x152bbded0>: Failed to resolve 'metadata.google.internal' ([Errno 8] nodename nor servname provided, or not known)"))
2024-09-14 19:45:35 - WARNING - Compute Engine Metadata server unavailable on attempt 3 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x152bbe6e0>: Failed to resolve 'metadata.google.internal' ([Errno 8] nodename nor servname provided, or not known)"))
2024-09-14 19:45:40 - WARNING - Compute Engine Metadata server unavailable on attempt 4 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x152bbeaa0>: Failed to resolve 'metadata.google.internal' ([Errno 8] nodename nor servname provided, or not known)"))
2024-09-14 19:45:48 - WARNING - Compute Engine Metadata server unavailable on attempt 5 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x152bbef80>: Failed to resolve 'metadata.google.internal' ([Errno 8] nodename nor servname provided, or not known)"))
2024-09-14 19:45:49 - INFO - Dask dashboard available at http://127.0.0.1:59893/status
2024-09-14 19:45:49 - INFO - Listing files from 2022-01-01 00:00:00 to 2022-01-01 00:00:00.
2024-09-14 19:45:49 - INFO - Processing file: gs://gcp-public-data-arco-era5/raw/date-variable-single_level/2022/01/01/total_precipitation/surface.nc
2024-09-14 19:45:53 - INFO - File processed: gs://gcp-public-data-arco-era5/raw/date-variable-single_level/2022/01/01/total_precipitation/surface.nc with shape: (3636140, 3). Time taken: 4.40 seconds
2024-09-14 19:46:04 - INFO - Saving the combined DataFrame to Parquet.
2024-09-14 19:46:59 - INFO - Pipeline started.
2024-09-14 19:47:02 - WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
2024-09-14 19:47:06 - WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
2024-09-14 19:47:08 - WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 64] Host is down
2024-09-14 19:47:08 - WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
2024-09-14 19:47:08 - WARNING - Compute Engine Metadata server unavailable on attempt 1 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x15f76cc10>: Failed to resolve 'metadata.google.internal' ([Errno 8] nodename nor servname provided, or not known)"))
2024-09-14 19:47:09 - WARNING - Compute Engine Metadata server unavailable on attempt 2 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x15f76ded0>: Failed to resolve 'metadata.google.internal' ([Errno 8] nodename nor servname provided, or not known)"))
2024-09-14 19:47:11 - WARNING - Compute Engine Metadata server unavailable on attempt 3 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x15f76e6e0>: Failed to resolve 'metadata.google.internal' ([Errno 8] nodename nor servname provided, or not known)"))
2024-09-14 19:47:15 - WARNING - Compute Engine Metadata server unavailable on attempt 4 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x15f76eaa0>: Failed to resolve 'metadata.google.internal' ([Errno 8] nodename nor servname provided, or not known)"))
2024-09-14 19:47:23 - WARNING - Compute Engine Metadata server unavailable on attempt 5 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x15f76ef80>: Failed to resolve 'metadata.google.internal' ([Errno 8] nodename nor servname provided, or not known)"))
2024-09-14 19:47:24 - INFO - Dask dashboard available at http://127.0.0.1:59946/status
2024-09-14 19:47:24 - INFO - Listing files from 2022-01-01 00:00:00 to 2022-01-01 00:00:00.
2024-09-14 19:47:24 - INFO - Processing file: gs://gcp-public-data-arco-era5/raw/date-variable-single_level/2022/01/01/total_precipitation/surface.nc
2024-09-14 19:47:29 - INFO - File processed: gs://gcp-public-data-arco-era5/raw/date-variable-single_level/2022/01/01/total_precipitation/surface.nc with shape: (3636140, 3). Time taken: 4.32 seconds
2024-09-14 19:47:40 - INFO - Saving the combined DataFrame to Parquet.
2024-09-14 19:47:55 - INFO - Data saved to Parquet. Time taken: 15.64 seconds
2024-09-14 19:47:55 - INFO - Pipeline completed successfully in 56.28 seconds.
